#!/usr/bin/env python2
#
# Runs all tests, stops if something goes wrong.
#
# This file is part of Myokit
#  Copyright 2011-2018 Maastricht University, University of Oxford
#  Licensed under the GNU General Public License v3.0
#  See: http://myokit.org
#
import os
import sys
import subprocess

# Get test directory
path = os.path.abspath(os.path.dirname(__file__))

# Run method
def run(cmd):
    cmd = str(cmd)
    print('=== Running ' + cmd + ' ===')
    process = subprocess.Popen(os.path.join(path, cmd))
    try:
        process.communicate()
        exit_code = process.wait()
        if exit_code:
            print('Errors found in "' + cmd + '"')
            print('Halting')
            sys.exit(exit_code)
    except KeyboardInterrupt:
        print('Terminating...')
        process.terminate()
        raise
    
# Run all
run('run')
run('web')
run('pub')
