#!/usr/bin/env python2
#
# Runs all example scripts currently written for the myokit website.
#
# This file is part of Myokit
#  Copyright 2011-2018 Maastricht University, University of Oxford
#  Licensed under the GNU General Public License v3.0
#  See: http://myokit.org
#
import os
import sys
from runner import run

# Get file directory
path = os.path.abspath(os.path.dirname(__file__))

# Go up one step
path = os.path.dirname(path)

# Now go into web
path_html = os.path.join(path, 'web', 'html')
path_examples = os.path.join(path_html, 'static','download','data','examples')

# Run
args = list(sys.argv)
if len(args) > 1:
    # Run specific file
    args.pop(0)
    while args:
        run(path_examples, args.pop(0))
else:
    # Run all
    run(path_examples)
