#!/usr/bin/env python
import myokit
import myokit.lib.hh as hh

import os
import matplotlib.pyplot as plt

fname = os.path.join('tests', 'data', 'lr-1991-fitting.mmt')
model = myokit.load_model(fname)
model.get('membrane.V').set_rhs(-40)

model.get('membrane.V').set_binding('pace')

vs = [-30, -20, -10]
p = myokit.pacing.steptrain(
    vsteps=vs,
    vhold=-120,
    tpre=8,
    tstep=2,
    tpost=0)
t = p.characteristic_time()

s = myokit.Simulation(model, p)
d = s.run(5)
print(d.keys())

plt.figure()
plt.plot(d.time(), d['membrane.V'])
plt.show()

