#!/usr/bin/env python
import myokit
import myokit.formats
import myokit.formats.easyml
import myokit.lib.guess as guess

# Load CellML model
importer = myokit.formats.importer('cellml')
model = importer.model('decker_2009.cellml')

# Remove hardcoded stimulus protocol, if any
guess.remove_embedded_protocol(model)

# Export to EasyML
exporter = myokit.formats.exporter('easyml')
exporter.model('decker_2009.model', model)
