#!/usr/bin/env python
import os
import myokit
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

myokit.DEBUG = False

# Run simulation
n = 20
m, p, _x = myokit.load(os.path.join('dev', 'web', 'examples', 'stewart-2009-cable.mmt'))
s = myokit.Simulation1d(m, p, n, rl=True)
s.set_conductance(9)
s.set_step_size(0.05)

b = myokit.Benchmarker()
d = s.run(600, log=['engine.time', 'membrane.V', 'calcium.Ca_i'])
print(b.time())

# Show figures
f = plt.figure()
x = f.gca(projection='3d')
z = np.ones(len(d['engine.time']))
for i in range(0, n):
    x.plot(d['engine.time'], z*i, d['membrane.V', i])
f = plt.figure()
x = f.gca(projection='3d')
for i in range(0, n):
    x.plot(d['engine.time'], z*i, d['calcium.Ca_i', i])
plt.show()
