#!/usr/bin/env python3
import myokit
import numpy as np
import matplotlib.pyplot as plt

m, p, _ = myokit.load('test.mmt')

# Run simulation
b = myokit.Benchmarker()
sensitivities=(
    ['membrane.V', 'ina.INa'],
    ['ina.gNa', 'init(ica.Ca_i)', 'ica.gCa']
)   # 8 / 16     0.0002            0.09
s = myokit.Simulation(m, p, sensitivities)
b.reset()
d, e = s.run(1000)
print(b.time())
e = np.array(e)


plt.figure()
plt.subplot(3, 1, 1)
plt.plot(d.time(), d['membrane.V'])
plt.subplot(3, 3, 4)
plt.plot(d.time(), e[:, 0, 0], label='dV/dgNa')
plt.legend()
plt.subplot(3, 3, 5)
plt.plot(d.time(), e[:, 0, 2], label='dV/dgCa')

plt.legend()
plt.subplot(3, 3, 6)
plt.plot(d.time(), e[:, 0, 1], label='dV/dCai0')
plt.legend()
plt.subplot(3, 3, 7)
plt.plot(d.time(), e[:, 1, 0], label='dINa/dgNa')
plt.xlim(50, 52)
plt.legend()
plt.subplot(3, 3, 8)
plt.plot(d.time(), e[:, 1, 2], label='dINa/dgCa')
plt.xlim(50, 52)
plt.legend()
plt.subplot(3, 3, 9)
plt.plot(d.time(), e[:, 1, 1], label='dINa/dCai0')
plt.legend()


plt.show()

