#!/usr/bin/env python3
import myokit
import numpy as np
import matplotlib.pyplot as plt

m, p, _ = myokit.load('~/dev/models/tentusscher-2006.mmt')

easy = True

# Run simulation
s = myokit.Simulation(m, p)
d, e = s.run(1000, apd_variable='membrane.V', apd_threshold=-70)

print(e)

