name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: coverage
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          sudo .github/workflows/install-ubuntu-dependencies.sh

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[optional]
          python -m pip install coverage codecov
          python .github/workflows/select-opencl-device.py

      - name: Show Myokit info
        run: |
          python -m myokit system
          python -m myokit opencl

      - name: Run coverage tests
        run: |
          coverage run -m myokit test unit

      - name: Submit report to codecov
        if: success()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          codecov
