name: Docs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: docs
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          sudo .github/workflows/install-ubuntu-dependencies.sh
          sudo apt update && sudo apt install -y libegl1-mesa-dev

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install .[docs,optional,gui]

      - name: Show Myokit info
        run: |
          python -m myokit system

      - name: Run doctests
        run: |
          python -m myokit test doc

