name: Docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install dependencies
        run: |
          sudo ./.github/workflows/install-ubuntu-dependencies.sh

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[docs,optional,gui]

      - name: Run doctests
        run: |
          python -m myokit system
          python -m myokit test doc

