name: Numpy 1.x unit test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: unit-numpy
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - name: Configure Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          sudo .github/workflows/install-ubuntu-dependencies.sh

      - name: Install Numpy 1.x
        run: |
          python -m pip install "numpy<2"

      - name: Install Myokit
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[optional]
          python .github/workflows/select-opencl-device.py

      - name: Show Myokit info
        run: |
          python -m myokit system
          python -m myokit opencl

      - name: Run unit tests
        run: |
          python -m myokit test unit

